name: Build Microservices

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # ===== BUILD & INSTALL COMMON =====
      - name: Install common-utils
        working-directory: server/common-utils
        run: mvn clean install -DskipTests

      - name: Install common-security
        working-directory: server/common-security
        run: mvn clean install -DskipTests

      # ===== BUILD SERVICES =====
      - name: Build authservice
        working-directory: server/authservice
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: mvn clean package

      - name: Build user-service
        working-directory: server/user-service
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: mvn clean package
